# Generated by Django 5.2 on 2025-04-09 18:12

import django.contrib.postgres.constraints
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='hours',
            name='exclude_overlapping',
        ),
        migrations.AddConstraint(
            model_name='hours',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('restaurant', '='), ('day_of_week', '='), ('open_range', '&&'), ('datetime_range', '&&')], name='exclude_overlapping'),
        ),
    ]
