# Generated by Django 5.2 on 2025-04-09 21:48

import django.contrib.postgres.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_remove_hours_exclude_overlapping_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['pk']},
        ),
        migrations.RemoveConstraint(
            model_name='hours',
            name='exclude_overlapping',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddConstraint(
            model_name='hours',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('restaurant', '='), ('day_of_week', '='), ('open_range', '&&'), ('datetime_range', '&&')], name='exclude_overlapping_open_range'),
        ),
    ]
