services:
  web:
    build: .
    volumes:
      - runtime-data:/runtime
    ports:
      - "8000:8000"
    env_file:
      - .env_docker
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env_docker

volumes:
  runtime-data:
  postgres_data:
